/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

import controlador.Controlador;
import com.personal.utiles.FormularioUtil;
import com.personal.utiles.ParametrosUtil;
import com.personal.utiles.PropertiesUtil;
import java.lang.reflect.InvocationTargetException;
import java.util.Properties;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JComboBox;
import javax.swing.JFormattedTextField;
import javax.swing.JPasswordField;
import javax.swing.JTextField;
import org.apache.commons.beanutils.BeanUtils;
import utiles.Encriptador;

/**
 *
 * @author fesquivelc
 */
public class Configuracion extends javax.swing.JInternalFrame {

    /**
     * Creates new form Configuracion
     */
//    private final String urlRRHH;
//    private final String urlBIOSIS;
    private final String urlBIOSTAR;

//    private Properties rrhh;
//    private Properties biosis;
    private Properties biostar;

    public Configuracion() {
        initComponents();

//        urlRRHH = "config/rrhh-config.properties";
//        urlBIOSIS = "config/biosis-config.properties";
        urlBIOSTAR = "config/biostar-config.properties";

        mostrarValores();

    }

    private void mostrarValores() {
        //CARGANDO PROPIEDADES DE RECURSOS HUMANOS
//        rrhh = PropertiesUtil.cargarProperties(urlRRHH);
//        biosis = PropertiesUtil.cargarProperties(urlBIOSIS);
        biostar = PropertiesUtil.cargarProperties(urlBIOSTAR);

        cargar(biostar, cboTipoBD1, txtConexion1, txtUsuario1, txtPassword1);

    }

    private void cargar(Properties fichero, JComboBox combo, JTextField txtConexion, JTextField txtUsuario, JTextField txtPassword) {
        int tipoBD = Integer.parseInt(fichero.getProperty("tipo"));

//        String driver = ParametrosUtil.obtenerDriver(tipoBD);
        String url = fichero.getProperty("url");
        String usuario = fichero.getProperty("usuario");
        String password = fichero.getProperty("password");

        combo.setSelectedIndex(tipoBD - 1);
        txtConexion.setText(url);
        txtUsuario.setText(usuario);
        txtPassword.setText(Encriptador.decrypt(password));
    }

    private void guardar(Properties fichero, String urlFichero, JComboBox combo, JTextField txtConexion, JTextField txtUsuario, JTextField txtPassword) {

        int tipoBD = combo.getSelectedIndex() + 1;

//        String driver = ParametrosUtil.obtenerDriver(tipoBD);
        String url = txtConexion.getText();
        String usuario = txtUsuario.getText();
        String password = txtPassword.getText();

//        combo.setSelectedIndex(tipoBD - 1);
        txtConexion.setText(url);
        txtUsuario.setText(usuario);
        txtPassword.setText(password);
        
        fichero.setProperty("url", url);
        fichero.setProperty("usuario", usuario);
        fichero.setProperty("password", Encriptador.encrypt(password));
        fichero.setProperty("tipo", tipoBD+"");

        PropertiesUtil.guardarProperties(fichero, urlFichero);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        pnlBiostar = new javax.swing.JPanel();
        jLabel40 = new javax.swing.JLabel();
        jLabel41 = new javax.swing.JLabel();
        jLabel42 = new javax.swing.JLabel();
        jLabel43 = new javax.swing.JLabel();
        cboTipoBD1 = new javax.swing.JComboBox();
        txtConexion1 = new javax.swing.JTextField();
        txtUsuario1 = new javax.swing.JTextField();
        txtPassword1 = new javax.swing.JPasswordField();
        jButton2 = new javax.swing.JButton();

        setClosable(true);
        setTitle("Configuración de base de datos");
        getContentPane().setLayout(new java.awt.GridBagLayout());

        pnlBiostar.setBorder(javax.swing.BorderFactory.createTitledBorder("Datos de conexión a Biostar"));
        java.awt.GridBagLayout pnlBiostarLayout = new java.awt.GridBagLayout();
        pnlBiostarLayout.columnWidths = new int[] {0, 5, 0, 5, 0, 5, 0};
        pnlBiostarLayout.rowHeights = new int[] {0, 5, 0, 5, 0, 5, 0, 5, 0, 5, 0, 5, 0, 5, 0, 5, 0};
        pnlBiostar.setLayout(pnlBiostarLayout);

        jLabel40.setText("Conexión:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.weightx = 0.1;
        pnlBiostar.add(jLabel40, gridBagConstraints);

        jLabel41.setText("Usuario:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 8;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.weightx = 0.1;
        pnlBiostar.add(jLabel41, gridBagConstraints);

        jLabel42.setText("Contraseña:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 12;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.weightx = 0.1;
        pnlBiostar.add(jLabel42, gridBagConstraints);

        jLabel43.setText("Tipo de BD:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.weightx = 0.1;
        pnlBiostar.add(jLabel43, gridBagConstraints);

        cboTipoBD1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "SQL Server", "PostgreSQL", "MySQL" }));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.weightx = 0.1;
        pnlBiostar.add(cboTipoBD1, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.weightx = 0.1;
        pnlBiostar.add(txtConexion1, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 8;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.weightx = 0.1;
        pnlBiostar.add(txtUsuario1, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 12;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.weightx = 0.1;
        pnlBiostar.add(txtPassword1, gridBagConstraints);

        jButton2.setText("Guardar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 16;
        gridBagConstraints.gridwidth = 7;
        gridBagConstraints.weightx = 0.1;
        pnlBiostar.add(jButton2, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 0.1;
        gridBagConstraints.weighty = 0.1;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        getContentPane().add(pnlBiostar, gridBagConstraints);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        this.guardar(biostar, urlBIOSTAR, cboTipoBD1, txtConexion1, txtUsuario1, txtPassword1);
       FormularioUtil.mensajeExito(this, Controlador.NUEVO);
    }//GEN-LAST:event_jButton2ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox cboTipoBD1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel40;
    private javax.swing.JLabel jLabel41;
    private javax.swing.JLabel jLabel42;
    private javax.swing.JLabel jLabel43;
    private javax.swing.JPanel pnlBiostar;
    private javax.swing.JTextField txtConexion1;
    private javax.swing.JPasswordField txtPassword1;
    private javax.swing.JTextField txtUsuario1;
    // End of variables declaration//GEN-END:variables

    private void inicializar() {

    }

    private void guardar(Properties fichero, String urlFichero, JComboBox combo, JTextField txtConexion, JTextField txtUsuario, JTextField txtPassword, boolean selected) {
        int tipoBD = combo.getSelectedIndex() + 1;

//        String driver = ParametrosUtil.obtenerDriver(tipoBD);
        String url = txtConexion.getText();
        String usuario = txtUsuario.getText();
        String password = txtPassword.getText();

//        combo.setSelectedIndex(tipoBD - 1);
        txtConexion.setText(url);
        txtUsuario.setText(usuario);
        txtPassword.setText(password);
        
        fichero.setProperty("url", url);
        fichero.setProperty("usuario", usuario);
        fichero.setProperty("password", Encriptador.encrypt(password));
        fichero.setProperty("tipo", tipoBD+"");
        
        if(selected){
            fichero.setProperty("action", "create");
        }else{
            fichero.setProperty("action", "none");
        }

        PropertiesUtil.guardarProperties(fichero, urlFichero);
    }

}
